### ISSUE TITLE
using multiple .files() ?

### ISSUE THREAD

**Issue by carpii** [indexzero/nconf#110]
I am trying to use two calls to file(), in the hope any elements present in one file will override those in the other

```
nconf.argv().env().file({file: 'nconf.json'}).file({file: 'host.json'});
```

If I util.inspect(nconf) it seems like the stores object is only able to hold one file store at a time, so nconf.json is being replaced entirely by host.json. 

Is this a known issue, or have I misunderstood something?

**Comment by marcellodesales** [comment]
I ran into a situation that the name of the store being "overrides" and "defaults" completely wipes out the stores for the call `nconf.defaults()` and `nconf.overrides()`. 

@vegar is this correct? I did the following to prevent that:

```js
/**
 * Loads a given file based on the name.
 *
 * @param {string} appConfigDir the path to the file.
 * @param {string} fileName the name of the file.
 * @param {string} format is the format to be loaded.
 */
function _loadFile(appConfigDir, fileName, format) {
  var filePath = path.resolve(appConfigDir, fileName + "." + format);
  log.debug("Attempting to load the " + fileName + " file at " + filePath);

  if (format === "json") {
    nconf.file(fileName + "-store", filePath);

  } else {
    // load a yaml file using a custom formatter
    // https://gist.github.com/clarkdave/f31d92ca88d11ef5340c
    nconf.file({
      file: filePath + "-store",
      format: {
        parse: yaml.safeLoad,
        stringify: yaml.safeDump,
      }
    });
  }
}
```
