### ISSUE TITLE
Support mandatory options

### ISSUE THREAD

**Issue by jwarkentin** [indexzero/nconf#128]
There's a way to require certain command line options with optimist, but there is no way to require that some option is specified regardless of source. Perhaps a simple implementation could simply iterate over a set of options and do a `get()` on each one and throw an error if a required option is missing. The usage could look something like this:

``` js
try {
  nconf.require(['db:host', 'db:user', 'db:password']);
} catch(e) {
  console.error(e.message);
  process.exit();
}
```

The message could just be something like `Missing required option 'db:host'` if it's not given anywhere.

**Comment by indexzero** [comment]
@jwarkentin pull-requests welcome :muscle: :100:

**Comment by jwarkentin** [comment]
I don't have a ton of time to figure out how to get it setup for testing and write tests for it, but here's the code I've been using in my projects for this:

```js
nconf.require = function require(options) {
  var missing = [];
  for(var i = 0; i < options.length; ++i) {
    if(!nconf.get(options[i])) {
      missing.push(options[i]);
    }
  }

  if(missing.length) {
    throw new Error("Missing required option" + (missing.length > 1 ? 's' : '') + " '" + missing.join("', '") + "'");
  }
};
```

And then I just call it like this:
```js
try {
  nconf.require(['bindHost', 'bindPort', 'journalDir']);
} catch(e) {
  console.error(e.message);
  process.exit(1);
}
```

The exception is important because the program can't continue on with required options missing, but I just like to catch it and handle it to avoid the stack trace dump.

**Comment by indexzero** [comment]
@jwarkentin ok. I don't have a ton of time either, so hopefully some kind and gentle open source soul comes and turns this into a pull-request. Thanks.
