### ISSUE TITLE
Support using nconf in a (browserify-based) browser context

### ISSUE THREAD

**Issue by ronjouch** [indexzero/nconf#130]
Hi.

Like [StackOverflow post "using nconf in the browser"](http://stackoverflow.com/questions/27297709/using-nconf-in-the-browser), I'm trying to use your package in a browserify setup, but because nconf calls `fs.readdirSync` when it is `require()`d to scan directories for configuration, it fails in the browser.

→ Is it something that sounds feasible with nconf, or do you suggest going for another package / custom solution?

Thanks for the help, and sorry for posting this as an issue, it's more of a question to which _"we do not and will not support that"_ can be a fine answer.

**Comment by naoufal** [comment]
+1

**Comment by ronjouch** [comment]
OP here. @toddpi314 @naoufal, I ended up using mozilla's [convict](https://github.com/mozilla/node-convict/) module, which I bent to my browser needs through a little intermediate layer using superagent. See discussion in https://github.com/mozilla/node-convict/issues/47 , which lead to a solution now [documented in their README.md](https://github.com/mozilla/node-convict#how-can-i-use-convict-in-a-browserify-based-browser-context) and probably applicable to nconf too:

* Ignore the `system` and `file` modules (in Gulp, add `.ignore('system').ignore('file')` to your browserify pipe).
* Use [`brfs`](https://www.npmjs.com/package/brfs) to ensure the `fs.loadFileSync` schema-loading calls are inlined at build time rather than resolved at runtime (in Gulp, add `.transform(brfs)` to your browserify pipe).
* To support *"loading configuration from a `http://foo.bar/some.json` URL"*, build a thin wrapper around convict using your favorite http package (e.g. [`superagent`](https://visionmedia.github.io/superagent/)). Typically, in the success callback, call convict's `load()` on the body of the response.

@indexzero @jcrugzz if you deem this solution applicable and acceptable in nconf, feel free to close.

**Comment by naoufal** [comment]
Thanks @ronjouch.  I'll give that a shot and report back.

**Comment by indexzero** [comment]
Not sure I follow: **_is it lazy-loading or lazy-loading the directory?_** In other words, does d501e7b fix it?

**Comment by tragiclifestories** [comment]
@indexzero It fixed it for me, FWIW. I'm using browserify.

**Comment by mrfelton** [comment]
When I use d501e7b I get a different error

```
Error: Cannot find module './nconf/stores/env'
```

**Comment by particle4dev** [comment]
Hi,
I still get this error in v0.7.1. Have you guys fixed it ?
```Uncaught TypeError: fs.readdirSync is not a function```
It will be great if we can get nconf work in a browser. We can built isomorphic web.
cc @indexzero

**Comment by abec** [comment]
d501e7b fixes things for me as well. Using webpack.

**Comment by fikriauliya** [comment]
As mentioned above, https://github.com/indexzero/nconf/commit/d501e7b04ce0c04b950f94ca8b7d31d26e50fc61 fix the issue by removing the usage of `fs`. However, the current code uses `fs` again

**Comment by syarul** [comment]
Still getting error after compiling with browserify

``return new (require('../nconf')[common.capitalize(type.toLowerCase())])(opti``

``TypeError: object is not a function``

**Comment by evoye** [comment]
also webpack builds for a nodejs context fails with "Error: ENOENT: no such file or directory, scandir '//nconf/stores'" due to the lazy loading pattern based on fs.
