### ISSUE TITLE
Arrays support

### ISSUE THREAD

**Issue by vbauer** [indexzero/nconf#131]
Could you please clarify in the README file how to specify "array" parameters for nconf.argv (or nconf.env)?

**Comment by chmontgomery** [comment]
:+1:

**Comment by sentient** [comment]
It seems that if you duplicate your environment key, that it is being added
e.g.
MyArrayItems = [10,20]

node myapp.js --MyArrayItems=10 --MyArrayItems=20

**Comment by kirrg001** [comment]
Any idea how this works for env parameters?

**Comment by MadLittleMods** [comment]
@mhamann This issue can be closed because https://github.com/indexzero/nconf/pull/272 is now merged.

`somelist="[1, 2, 3]" node test.js`
```js
nconf.env({ parseValues: true });
const somelist = nconf.get('somelist') // Array [1, 2, 3]
```

**Comment by mhamann** [comment]
Good call, thanks.
