### ISSUE TITLE
Wiki for Config Formats

### ISSUE THREAD

**Issue by laktak** [indexzero/nconf#140]
Would it be possible to enable the wiki for nconf?

I'd like to document how you can use it with [Hjson](http://laktak.github.io/hjson).

E.g.

---
## Hjson

Hjson follows the JSON syntax but makes quotes and commas optional:

```
{
  // add comments
  database:
  {
    host: 127.0.0.1
    port: 5984
  }
}
```

[Syntax](http://laktak.github.io/hjson)

### Usage:

```
nconf.file({ file: 'file.hjson', format: require('hjson').rt });
```

---

**Comment by Oza94** [comment]
+1, I would like to enhance documentation on `nconf.get()` and providers. The actual README is not complete.

**Comment by indexzero** [comment]
Closing in favor of a larger tracking issue #160.
