### ISSUE TITLE
.load() should be synchronous

### ISSUE THREAD

**Issue by irony** [indexzero/nconf#147]
Since most of the architecture of nconf is synchronous, why is .load({file:..}) not? If you do pass a callback function it should be async, otherwise you tend to get very hard errors to understand. The load method is only used in startup so it should be fairly ok performance wise to do this.

**Comment by ErikEvenson** [comment]
I disagree with this.  Methods should be consistently async or sync regardless of the presence of a callback.  A good explanation of why is available here under item 3: http://caolanmcmahon.com/posts/nodejs_style_and_structure/.  A synchronous load, if provided should be .loadSync() IMHO.  Cheers.

**Comment by indexzero** [comment]
Load will remain async, but `get` will become sync.
