### ISSUE TITLE
Serialize current config state

### ISSUE THREAD

**Issue by Aetet** [indexzero/nconf#148]
Is it possible to serialize current config state to plain js-object?

**Comment by olalonde** [comment]
:+1: Also would need this...

**Comment by Oza94** [comment]
I'm not sure to understand but `nconf.get();` must be what you are looking for:

```javascript
nconf.get(); // return full configuration as js object
```

Howerver, this is not described in the README

**Comment by indexzero** [comment]
Closing in favor of a larger tracking issue #160.
