### ISSUE TITLE
Case insensitive option?

### ISSUE THREAD

**Issue by olalonde** [indexzero/nconf#155]
I would like to all my environment variables to be overridden by equivalent argv arguments. The problem is that by convention, environment vars are typically uppercase while argvs are lower case. I was wondering if there was a way to tell nconf that nconf.get('SOMETHING') is the same as nconf.get('something'). Is that possible?

**Comment by olalonde** [comment]
Used this as a quick workaround:

```javascript
  // Case insensitive env variables
  Object.keys(process.env).forEach(function (key) {
    process.env[key.toLowerCase()] = process.env[key];
  });
```

**Comment by friederbluemle** [comment]
Thanks for opening this issue, I was just thinking about it. It would be nice to have a real clean nconf solution at some point.

**Comment by olalonde** [comment]
Opened a pull request here: https://github.com/indexzero/nconf/pull/177

**Comment by josephpage** [comment]
:+1:

**Comment by danielkrainas** [comment]
can this be closed? it's misleading to see it open since the PR was merged.
