### ISSUE TITLE
Error when removing file from nconf and afterwards saving

### ISSUE THREAD

**Issue by Eragon666** [indexzero/nconf#161]
Hello,

I am struggling with a strange error in nconf. I used NCONF to load custom config for a short time to get some data, I use the temp name and load it into nconf. But if the sytem is processing some config items (loading and unloading into nconf) and simultaniously tries to save nconf a error appears. 

It looks like the problem only happens after a store is removed. This is the error: 

```
TypeError: Cannot read property 'save' of undefined                                                                                                                                                                                           
    at saveStore (/home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/provider.js:464:14)                                                                                                                                      
    at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:272:13                                                                                                                                        
    at iterate (/home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:149:13)                                                                                                                              
    at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:160:25                                                                                                                                        
    at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:274:17                                                                                                                                        
    at /home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/provider.js:474:9                                                                                                                                                   
    at /home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/stores/file.js:57:34                                                                                                                                                
    at Object.oncomplete (fs.js:107:15)   
```

Is there a known solution to this error?

**Comment by Oza94** [comment]
I'm not sure to understand your use case but if I understand well, you feed nconf with a file, then try to remove it before nconf has processed the file and it gives you an error?

When you use `.file()` nconf will try to load synchronously so you should not encounter issues on the function call is done. Also nconf never saves without explicit call the configuration to the file. 

Its hard to diagnose without code, can you provide a short snippet that reproduce the issue?

**Comment by Eragon666** [comment]
Hello Oza94,

Thanks for the reply!

Yeah it was hard to explain, but I will try to do my best to give a better explanation. 

The main application loads a default config.json. 

Another script checks a folder for new plugins, if a new plugin is found the config.json file inside the plugin directory is loaded into nconf. I do this with a sync function called 'loadCustomConfig'

Here is a stripped version of the code:
```javascript
        var name = 'temp';

        //Make sure the file exists, else just return
	if (!util.fileExists(abspath)) return;

	try {
		nconf.use(name, { type: 'file', file: abspath });
	} catch (e) {
		return false;
	}
	
	return name;
```

After the file is loaded I use the name to get the data from the file with a custom function which uses nconf.get() internally:

```javascript
var pluginid = config.getConfiguration('packageconfig:id');
```javascript

The json in the file is an object like this:
```json
packageconfig: {
   id: 4,
   name: example
}
```

So this script returns the id from the file (and that did work.)

But after I got all the information I need, I remove the file from NCONF with 

```javascript
config.removeCustomConfig({name: confName});

config file:
function removeCustomConfig(options) {
    var name = options.name;

   nconf.remove(name);
}
```

So the file is now succesfully removed, but when another script is calling my saveFunction (which uses nconf.save(function(err) {}); I get the error:

```javascript
TypeError: Cannot read property 'save' of undefined

at saveStore (/home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/provider.js:464:14)

at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:272:13

at iterate (/home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:149:13)

at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:160:25

at /home/cabox/workspace/home-automation/node_modules/nconf/node_modules/async/lib/async.js:274:17

at /home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/provider.js:474:9

at /home/cabox/workspace/home-automation/node_modules/nconf/lib/nconf/stores/file.js:57:34

at Object.oncomplete (fs.js:107:15)
```

I hope this helps, if you need more info please let me know

**Comment by Oza94** [comment]
Okay I think I've found the problem. You're using `nconf.use()` with the first parameter used as an identifier for the plugin configuration right? e.g. it will be something like `nconf.use('my-awesome-plugin', ...)`.

Actually the first parameter of `nconf.use()` is the name of the store to use : 
 * file
 * argv
 * env
 * ect.

You can see it [here](https://github.com/indexzero/nconf/blob/master/lib/nconf/provider.js#L92). Also you're using `options.name` which should override the first parameter, I believe. Indeed, [a local variable `type` is initialized](https://github.com/indexzero/nconf/blob/master/lib/nconf/provider.js#L94) but [not used when getting the store](https://github.com/indexzero/nconf/blob/master/lib/nconf/provider.js#L102) and never used at all. **This is probably a bug.**

I think [`nconf.add()`](https://github.com/indexzero/nconf/blob/master/lib/nconf/provider.js#L126) is what you are looking for.

We really need a better documentation on this project, see #160 if you want to make suggestions :)

**Comment by Eragon666** [comment]
Yeah I already found out that I couldn't do anything with the given name given to nconf.use(*name*). 
It looks like the loading with nconf.add() is still working, so I will use that instead of nconf.use().

Indeed the documentation is ok for simple using, but when you need to do more advanced stuff there is a lack of correct information.  I will think about other suggestions for the documentation!

Thanks for the quick replies!

**Comment by indexzero** [comment]
Thanks for your help @Oza94. This will definitely need to be part of the documentation in #160.
