### ISSUE TITLE
Supplying Array through the form of JSONString

### ISSUE THREAD

**Issue by yahudev** [indexzero/nconf#175]
Currently there's no way to supply array based json configuration. This addition allow you to apply the env configuration as a any json object, which also allows supplying Arrays.

I've created a Pull Request for this already. https://github.com/indexzero/nconf/pull/174

**Comment by yahu577** [comment]
@indexzero , would be great if you can do a quick review and give your thoughts on it.

**Comment by yahu577** [comment]
@indexzero, updated. thanks.

**Comment by yahu577** [comment]
@indexzero, any comment? thanks :)
