### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by AuspeXeu** [indexzero/nconf#180]
Could you please update the dependencies? :)

**Comment by josephpage** [comment]
Dependency | Actual | Latest | Status | PR
------------ | ------------- | ------------- |  ------------- |  ------------- | 
[async](https://www.npmjs.com/package/async) |  0.9.x | 1.4.2 | :warning: | #171 (tests failed)
[ini](https://www.npmjs.com/package/ini) | 1.x.x | 1.3.4 | :white_check_mark: |
[yargs](https://www.npmjs.com/package/yargs) | 3.15.x | 3.18.0 | :warning: | PR accepted |

Bonus : https://david-dm.org/indexzero/nconf

**Comment by josephpage** [comment]
#171 is merged and all dependencies are now up to date.
