### ISSUE TITLE
80ec01b (optimist -> yargs) breaks nconf.argv

### ISSUE THREAD

**Issue by dantman** [indexzero/nconf#181]
0.7.2 is a breaking and buggy change due to 80ec01b.

[This loop](https://github.com/indexzero/nconf/blob/80ec01b91d057656bfd18c303c9302f93def9dfc/lib/nconf/stores/argv.js#L60-L62) sets all the args parsed from argv on the store.

However optimist and yargs behave differently. Optimist omits all args that are not set even when defined by options. Yargs will instead set a property with the value undefined for any argument not passed to the program.
```js
> require('optimist').options({port: {alias: 'p'}}).argv
{ _: [], '$0': 'node' }
> require('yargs').options({port: {alias: 'p'}}).argv
{ _: [], '$0': '', port: undefined }
```

The result is that when using nconf.argv any option you define but do not pass to the program is set to undefined at the .argv level which will override any value further down the chain.

ie: If you define a --port/-p option with .argv, then accept port definitions from ENV, then fall back to a value in a config file – if you do not pass -p, port will be set to undefined and the ENV and config file settings will not be used.

**Comment by jcrugzz** [comment]
@dantman awesome find! Could you post a patch for this? `yargs` makes sense going forward but we obviously need a test and should adjust accordingly with the behavior.
