### ISSUE TITLE
"nconf.env" ignores "NODE_ENV" with specific options

### ISSUE THREAD

**Issue by mdreizin** [indexzero/nconf#234]
```
NODE_ENV=test npm run test
```

``` js
nconf.env({ lowerCase: true, separator: '_' });
```

``` js
CONFIG.get('node:env'); // undefined
```

**Comment by vivekannan** [comment]
I don't think this is a bug. You have specified that the env variables should be loaded in lowerCase and that the separator is '_'.

So nconf loads 'NODE_ENV' as
    
    "env": {
        "node_env": "test"
     }

So, you should get it using,

    CONFIG.get('node_env');

The `separator` is used to fetch keys from nested objects,

    nconf.file('someFile', {
         file:'somePath',
         separator: '_'
    });

Gets loaded as,

    'someFile': {
        "some": {
            "nested": {
                   "config": "value"
            }
        }
    }
    
    CONFIG.get("some_nested_config"); // "value"

**Comment by mdreizin** [comment]
@vivekannan Please look at steps to reproduce the issue:

1. `NODE_ENV=test npm run test`
2. `nconf.env({ lowerCase: true, separator: '_' });`
3. `console.log('node_env', nconf.get('node_env'));` -> `undefined` ???
4. `console.log('NODE:ENV', nconf.get('NODE:ENV'));` -> `test` ???
4. `console.log('node:env', nconf.get('node:env'));` -> `test` ???

**PS**: I completely understand how `nconf` and especially [`nconf.env`](https://github.com/indexzero/nconf/blob/master/lib/nconf/stores/env.js#L57) work.

**Comment by simonrenoult** [comment]
@vivekannan You seem to misunderstand what `lowerCase` does.

As [written in the code](https://github.com/indexzero/nconf/blob/0c5774fec798e50c5749e8de6f6f77875fef2b02/lib/nconf/stores/env.js#L62), the flag `lowerCase` allows to ignore whether an environment variable is uppercased or lowercased, hence `port` and `PORT` are both accessible with `nconf.get('port')` when `lowerCase` is `true`. Though this feature does not seem to be mentioned in the documentation.

As for the issue itself, I can't reproduce the bug with `nconf@0.8.4` you are reporting, as show in the code below:
```js
const nconf = require('nconf')
const assert = require('assert')

describe('use nconf.get() to retrieve NODE_ENV', () => {
  context('when nconf has no parameter', () => {
    it('returns NODE_ENV', () => {
      process.env.NODE_ENV = 'fakeNodeEnv'
      nconf.env()
      assert.equal(nconf.get('NODE_ENV'), 'fakeNodeEnv')
      assert.notEqual(nconf.get('node_env'), 'fakeNodeEnv')
    })
  })
  context('when lowerCase is true', () => {
    context('when separator is not set', () => {
      it('returns NODE_ENV', () => {
        process.env.NODE_ENV = 'fakeNodeEnv'
        nconf.env({lowerCase: true})
        assert.equal(nconf.get('node_env'), 'fakeNodeEnv')
        assert.equal(nconf.get('NODE_ENV'), 'fakeNodeEnv')
      })
    })
    context('when separator is set', () => {
      it('returns NODE_ENV', () => {
        process.env.NODE_ENV = 'fakeNodeEnv'
        nconf.env({lowerCase: true, separator: '_'})
        assert.equal(nconf.get('node:env'), 'fakeNodeEnv')
        assert.equal(nconf.get('NODE:ENV'), 'fakeNodeEnv')
        assert.notEqual(nconf.get('NODE_ENV'), 'fakeNodeEnv')
        assert.notEqual(nconf.get('node_env'), 'fakeNodeEnv')
      })
    })
  })
})
```

**Comment by Alexsey** [comment]
@mdreizin It looks like now it works as expected
