### ISSUE TITLE
I can't figure out how to override values

### ISSUE THREAD

**Issue by justinmchase** [indexzero/nconf#235]
Neither of these seem to work for me and I don't understand why:

``` js
import nconf from 'nconf'
nconf.add('test', { type: 'literal', store: { example: 1 } })

// setting...
nconf.set('example', 2)
assert(nconf.get('example') === 2) // err

// overriding...
nconf.overrides({ example: 2 })
assert(nconf.get('example') === 2) // err
```

How do I set a value after an add that takes precedent? Basically I want to override a couple values during tests.

**Comment by brandon-collins** [comment]
look at this: https://github.com/indexzero/nconf/issues/197

**Comment by Alex-Mann** [comment]
Is there a way to completely remove a key/value? I have tried clear and remove and both have not worked.
