### ISSUE TITLE
Nested config over environment variables

### ISSUE THREAD

**Issue by strarsis** [indexzero/nconf#238]
How can I pass nested configuration over environment variables?
What delimiter can I use for separating keys?
It would be helpful when an example is added to documentation.

**Comment by strarsis** [comment]
Colons (:) cause trouble/aren't possible in environment variable names.

I found a tutorial page where environment variables with separator are used: http://www.codedependant.net/2015/01/31/production-ready-node-configuration/

This example allows to use environment variables with double underscore (__) separator:
````
[...]
nconf
.env({separator:'__'}) 
[...]
````

````
export db__host="test"
````
equal to
````
db:host="test"
````

**Comment by simonrenoult** [comment]
This feature is already mentioned in the documentation: https://github.com/indexzero/nconf#env

**Comment by Redsandro** [comment]
> Colons (:) cause trouble

@strarsis the trouble causing colon seems arbitrary; in some situations they work fine: #336. Have you figured out why they _sometimes_ don't work?

Sorry for bumping an old issue. Google brought me here. It is still relevant.

**Comment by linqFR** [comment]
> This feature is already mentioned in the documentation: https://github.com/indexzero/nconf#env

Hello
well to be honest : the explanation is not clear !

- **will .env('--' ) change separator only for env store or all stores?**
i tried many ways and so far just seems to work on env !

- **how do i change default separator for files or in memory ?**
- **will the new separator always work for .required()?**
- **I saw some explanation over internet about env({separator:'xx',whitelist:['blah','bloah']}) : can you explain/document more in details? Is this working also for file && memory stores?**

**Comment by mhamann** [comment]
I agree--this feature doesn't necessarily work how you might expect. This PR is a breaking change, but I think makes it clearer. Feedback welcome: https://github.com/indexzero/nconf/pull/337

**Comment by linqFR** [comment]
@mhamann 
thank you

what about .required() and whitelist?
