### ISSUE TITLE
env ignores lowerCase option

### ISSUE THREAD

**Issue by OmgImAlexis** [indexzero/nconf#261]
I don't know if I'm missing something or not reading the docs correctly and I'm hoping someone here can help. Currently I'm using this setup in my app with a `config.json` file in the root of my repo. If the app uses docker instead of just launching it via the cli I would like to use redis inside of another container hence the need for ENV.

What I've noticed is that even when passing in `DNS_PORT` it's being added to the store with all capitals meaning when `get()` is called it finds the lowercase one even since there's now two `DNS` and `dns` fields in the store.

Maybe the lowerCase option should add the fields using lowerCase instead of just looking them up with lowerCase?

```
nconf.use('file', {
    file: path.join(__dirname, 'config.json')
}).defaults({
    redis: {
        host: "127.0.0.1",
        port: 6379
    },
    dns: {
        port: 5353
    }
}).env({
    separator: '_',
    lowerCase: true,
    whitelist: [
        'DNS_INTERFACE',
        'DNS_PORT',
        'DNS_ZONE',
        'REDIS_HOST',
        'REDIS_PORT',
        'LOGS_LEVEL'
    ]
});
```

The last line uses `nconf.get('dns:port');` to set the server's port.
The output is from `console.log(nconf.get());`.

```
➜  redis-dns git:(master) ✗ export DNS_PORT=6000 && ./node_modules/.bin/babel-node index.js 
{ DNS: { PORT: '6000' },
  redis: { host: '127.0.0.1', port: 6379 },
  dns: { port: 2103, interface: '127.0.0.1', zone: 'redis-dns.local' },
  type: 'literal',
  logs: { level: 'warning' } }
Server running at 127.0.0.1:2103
```

**Comment by ifuyivara** [comment]
did you find the issue? I'm having the same problem here

**Comment by OmgImAlexis** [comment]
The issue is stated above. I ended up just switching to [configstore](https://www.npmjs.com/package/configstore).
