### ISSUE TITLE
Chainable .required() not present in 0.10.0 in npm

### ISSUE THREAD

**Issue by Sikian** [indexzero/nconf#295]
Hi guys,

I'm having some trouble using the required() as a chain as in the v.0.10.0 in npm it returns true (I can see that it was fixed in the last commit in that file). Could it be that it wasn't included in the latest release?

Thanks!

**Comment by mhamann** [comment]
Could you include code in your report? Thanks...

**Comment by mhamann** [comment]
@Sikian on taking a second look, 0.10 doesn't include this change due to the backwards-incompatible nature of changing the API. It will be included as part of v1.0 due out in the near future.

**Comment by Sikian** [comment]
I see, thanks! 
Is there any ETA on v1.0?
