### ISSUE TITLE
Warning: Use Cipheriv for counter mode of aes-256-ctr

### ISSUE THREAD

**Issue by bdharrington7** [indexzero/nconf#296]
Starting in at least node v8.7.0, this warning is emitted when using the default algorithm. The [recommended approach](https://github.com/nodejs/node/issues/16746) is to use an `iv` and call `crypto.createCipheriv(algorithm, key, iv)` instead of `crypto.createCipher(algorithm, key)`. I'm guessing this would change the API of secure-keys to require an `iv` in addition to a `secret` in the options to instantiate it.

**Comment by cacola** [comment]
how to fix

**Comment by bdharrington7** [comment]
@mhamann Any comment since this is a potential vulnerability?

**Comment by mhamann** [comment]
@bdharrington7 yes...obviously something that should be fixed. Unfortunately the easy fix requires the upstream to update first, and I don't think I've seen any progress there.

I would like to revisit the crypto that nconf uses at some point anyway, so maybe the guidance for now is simply to handle encrypted values outside of the package.

**Comment by bnoordhuis** [comment]
I left a comment on https://github.com/jcrugzz/secure-keys/issues/1.  I don't know critical the data is that nconf stores encrypted but an attacker that manages to obtain a ciphertext can decrypt other ciphertexts that were encrypted with the same secret.

**Comment by mhamann** [comment]
Thanks. Seems like `secure-keys` has been abandoned.

The next major release of nconf would be 1.0, which would be a good opportunity to re-work nconf's encrypted value capability. Any interest in PRing some enhancements in that area (specifically to remove the dependency on secure-keys)?

**Comment by bnoordhuis** [comment]
I've opened #299.

**Comment by nichojo89** [comment]
bump

**Comment by mhamann** [comment]
@nichojo89 this was mostly fixed in https://github.com/indexzero/nconf/pull/322, but still needs a few changes before releasing.

There will be a v1.0.0 beta in the future that contains this change. I'm working on the release for that as time allows.

**Comment by andreasonny83** [comment]
Any update on this? Node 8 is officially not supported from 2020. I believe the v1 needs to be released ASAP

**Comment by mhamann** [comment]
Hi there, thanks for the reminder on this. I'm fairly close to having a v1 beta available and I think a full v1 can follow on fairly quickly, given the breaking changes are not extensive.

I am hoping to have this available within the next two weeks. Feel free to hold me accountable! :-)

**Comment by andreasonny83** [comment]
@mhamann , 
just something else I forgot to mention in my previous message. There is a backward compatibility check in the code that still uses the deprecated `crypto.createDecipher` . This will still cause deprecation warnings output to the terminal with moder versions of NodeJS.
https://github.com/indexzero/nconf/blob/f1ca5f04de0eec55613de32a33b52a3caa9b42cf/lib/nconf/stores/file.js#L213

I was wandering if you're planning to remove that condition in the version 1.
Thanks again.

**Comment by mhamann** [comment]
@andreasonny83 yeah, i think we should remove deprecated APIs, since we're breaking a few things with this. feel free to submit a PR around it or I'll hopefully get to it here shortly.

**Comment by mhamann** [comment]
@andreasonny83 offending code has been removed and tests updated. I'll leave the PR (https://github.com/indexzero/nconf/pull/380) open for a bit before merging if you want to have a look.

**Comment by andreasonny83** [comment]
Thanks for sharing @mhamann . The PR looks good to me.
Looking forward to testing the new version.
Thanks

**Comment by andreasonny83** [comment]
@mhamann  Any ETA for releasing v1?

**Comment by mhamann** [comment]
v1 beta 1 coming this week!

**Comment by mhamann** [comment]
@andreasonny83 at long last, v1.0.0-beta.0 is now available on npm. To install, run `npm i nconf@beta`, but note you might run into some backward-incompatible stuff along the way.
