### ISSUE TITLE
Is the project abandonned ?

### ISSUE THREAD

**Issue by gallofeliz** [indexzero/nconf#305]
Hi,

Does the project continue to be maintened ?

Regards

**Comment by mhamann** [comment]
The project is maintained. If you find a bug or have an idea for an enhancement, please open an issue. Then, you should open a PR with the fix documented and tested ;-)

**Comment by gallofeliz** [comment]
I think that with 3255 stars and 239 forks, this project has a good potential. I would be able to participate but when I see 89 issues, and worst, 6 open pull request (one is from 2 feb 2015 !!!), it seems like totally frozen project !
