### ISSUE TITLE
nconf.get('key') returns undefined if dependency linked with npm link

### ISSUE THREAD

**Issue by mikicho** [indexzero/nconf#308]
I'm developing two projects, projectA depends on projectB, if I'm linking projectB(local dependency) into projectA, all `nconf.get` inside the projectB (the dependency) code returns `undefined`.

A project demonstration can be found [here](https://github.com/mikicho/nconf-npm_link)

**Comment by mhamann** [comment]
@mikicho your required `nconf` versions must match _exactly_ in order for connected projects to share the same singleton.

In your example, Project A uses 0.10.0 and Project B uses 0.8.5. Thus, Node will internally require two different versions and they won't share the same memory space.

If you ensure the versions match, then things should work as expected.

**Comment by mikicho** [comment]
@mhamann Thanks for quick response.
The difference between the versions was accidental, I updated my project and now `nconf` have version `0.10.0` on both projects.

**Comment by mikicho** [comment]
@mhamann Can you re-open this issue?

**Comment by mikicho** [comment]
I investigated it further, and I see that `required('nconf`) called twice (i.e: node does not return the cached version)
