### ISSUE TITLE
nconf.get('key') returns undefined if dependency linked with npm link

### ISSUE THREAD

**Issue by mikicho** [indexzero/nconf#310]
I'm developing two projects, projectA depends on projectB, if I'm linking projectB(local dependency) into projectA, all `nconf.get` inside the projectB (the dependency) code returns `undefined`.

A project demonstration can be found [here](https://github.com/mikicho/nconf-npm_link)

re-open #308 because:

> The difference between the versions was accidental, I updated my project and now nconf have version 0.10.0 on both projects, yet the same result.

Also, I understand why its behave like that. this is because `nconf` also installed in the linked project, and when its required `nconf` module in projectB, its create a new instance because the path is different.
We can do something about that?

**Comment by mhamann** [comment]
What version of node are you using?

**Comment by mhamann** [comment]
Also, using `npm link` isn't going to dedupe your dependencies like `npm install` does. So that's likely the root of your problem.

If you pack projectB and then install it into projectA, the problem likely goes away.

**Comment by mikicho** [comment]
> What version of node are you using?
8 LTS

> If you pack projectB and then install it into projectA, the problem likely goes away.
What do you mean pack projectB?

The scenario I demonstrate here is when someone develop 2 local packages that projectA (the big project) depends on the projectB (small package) and want to test projectB before he publish it to the registry.

**Comment by mhamann** [comment]
Run `npm pack` on projectB, then `npm install <tar>` on the resulting tar file. Then you can test it.

**Comment by mikicho** [comment]
This is convenient enough for me, thanks!
