### ISSUE TITLE
parseValues for string environment variable arrays should accept single AND double quotes

### ISSUE THREAD

**Issue by mikkotikkanen** [indexzero/nconf#311]
For some obscure reason environment variables only allow for string arrays to be parsed (`parseValues: true`) when values themselves are enclosed in double quotes. This should instead be allowed with either single (') or double (") quotes.

```
// WORKS - Double quote enclosing the strings is valid
'values=["value1", "value2", "value3"]'

// DOESN'T WORK - Single quote enclosing should be valid as well
"values=['value1', 'value2', 'value3']"
```

Only allowing double quotes makes for one confusing time trying to figure out why things wont parse correctly, especially as A) it's not mentioned in the documentation, B) documentation examples are single quoted and C) fe. docker-compose requires things to be fully double quoted anyways (so you need to escape instead of doing the logical thing and using single-quotes) as parts of it are parsed as JSON.

```
// You need to do this in docker-compose for things to parse correctly
"values=[\"value1\", \"value2\", \"value3\"]"
```

**Comment by mhamann** [comment]
Given the lack of response on this, I'm going to close it. If you want to respond to my comments above, feel free to do so and potentially re-open. :-)
