### ISSUE TITLE
how do I set an object with nconf

### ISSUE THREAD

**Issue by maku** [indexzero/nconf#333]
I would like to read a JSON (string) object from an env variable and set it in nconf.

e.g

```
const settingsAsJsonString = process.env[envVarName];
const settings = JSON.parse(settingsAsJsonString);
nconf.set(envVarName, settings)

```

But when I get the value from nconf I get always an JSON string but NOT the object.

How can I achieve to get the object back?? TIA

**Comment by mhamann** [comment]
@maku did you figure this out?

**Comment by maku** [comment]
@mhamann no I did not. I worked around and chose another solution...
