### ISSUE TITLE
Is this repo still maintain? need update about this library

### ISSUE THREAD

**Issue by jimblue** [indexzero/nconf#335]
Hi,

The last closed issue was on Juin 22th 2019 but the last NPM release is 2 years old :scream: !

Can you give a little feedback to nconf users to let us now if you still plan to maintain it?

Hope you understand what I'm looking for, just feedback basically. :smile: 

Thank you so much,

Cheers

**Comment by mhamann** [comment]
Yes, this library is still maintained. It's fairly mature, so updates aren't needed super frequently. Also, the folks maintaining this are fairly busy, so updates tend to be a little on the slow side. :-)

**Comment by jimblue** [comment]
Thanks for your fast answer :)
Indeed there is a lot of updates but what the point if they're no new release... 😞 

It's like smelling pizza while standing in very long line... at very end... it's torture

**Comment by gabrielstuff** [comment]
Hello @mhamann do you think that a security release and updated dependencies version could be push soon ? Many commits and improvement have been done since the 2 years old latest release on npm.

Thanks a lot for this great library which we use everyday !

**Comment by j0k3r** [comment]
I agree with @gabrielstuff, you should try to release a new version to fix security issues.

**Comment by imtase** [comment]
I agree with @gabrielstuff and @j0k3r, I'm also waiting for a release with security issues fix.

**Comment by botic** [comment]
Sorry to say, but I switched to https://github.com/mozilla/node-convict/tree/master/packages/convict …

**Comment by caciuto** [comment]
Ehi there! 
Is any help I can provide appriciated?
Is any author of this library available to spend some time to code-review me in case?

**Comment by ErisDS** [comment]
I have a feeling this entire module is blocked on a fear of shipping a 1.0.0 version, like it needs to be something special? (It doesn't)

Can I help to get it over the line in any way? 

I know the repo is cared about and maintained and it's just missing a more up-to-date and secure release to get it going again.

**Comment by mhamann** [comment]
The next release essentially needs to be a 1.0.0 due to some of the changes in flight.

Help is absolutely welcome--really comes down to having enough time to deal with the changes, etc.

I'll try to get to dependency updates soon, and potentially that could enable a v0.9.x bump.

**Comment by ErisDS** [comment]
I find once you break the seal on doing releases in a package, it all gets a lot less intimidating 😬 

It would be cool to either just release master as-is as 0.9.2 or bump lodash and then do it. Just to make sure the release process is known & maybe documented if there's anything special needed (don't think so).

If there are specific changes you'd like a hand with it'd be cool to either have an issue or a milestone so people can see what needs input.

Maybe also some people want to volunteer to clean up the issue list... I'm happy to do things like setup a stale bot. Really helps to see what things are most cared about!

**Comment by j0k3r** [comment]
Good news, v0.11.0 is out!
https://github.com/indexzero/nconf/releases/tag/v0.11.0

**Comment by jimblue** [comment]
Really happy close this issue, thanks 😄
