### ISSUE TITLE
mysql 8.0.19 and services disabled.

### ISSUE THREAD

**Issue by BrixSat** [indexzero/nconf#340]
I was using mysql 8.0.19 and had to downgrade due to a major issue.

The mysql version 8.0.19 with nconf is doing something that i cannot yet understand. The result of this combination is all paused checks and all "not monitored" checks are being parsed as regular and active checks, and also in my case one host is missing, a valid host disappears from the final config.

So to avoid major debug and stuff, since no errors are being shown i had to downgrade mysql. At the moment back to 5.7. 

If anyone finds a fix, please report here. 

Thanks in advance.

**Comment by mhamann** [comment]
I think you may be in the wrong place. Perhaps try https://github.com/nconf/nconf
