### ISSUE TITLE
Yargs vulnerable in published v0.10.0

### ISSUE THREAD

**Issue by JackuB** [indexzero/nconf#349]
Hi, there was a [new vulnerability in disclosed in the y18n module in yargs](https://snyk.io/vuln/SNYK-JS-Y18N-1021887) which is [affecting the nconf@0.10.0](https://snyk.io/test/npm/nconf@0.10.0) because the [published version is still using `yargs@^3.19.0`](https://unpkg.com/nconf@0.10.0/package.json). 

The issue should be solved by updating yargs to v16 for which there is already a PR https://github.com/indexzero/nconf/pull/347

Is there any chance that you'll merge the https://github.com/indexzero/nconf/pull/347 and release a new version of nconf to update yargs from version 3 to version 16?

**Comment by dargmuesli** [comment]
@mhamann seems like you took care of the latest merges? :)

**Comment by mhamann** [comment]
I'll take a look. Thanks for the heads up.

**Comment by mhamann** [comment]
This has been resolved by the release of v0.11.0.
