### ISSUE TITLE
0.12 release for ini vulnerability

### ISSUE THREAD

**Issue by gptt916** [indexzero/nconf#354]
Hi, when is the planned release for 0.12? current release has the vulnerability, master has already been patched.

**Comment by sitvanit** [comment]
+1 
We have the same vulnerability in our service, is there any plan to upgrade it in the near future?

**Comment by pankaj-kumar34** [comment]
+1

**Comment by mhamann** [comment]
The release fixing the ini vulnerability should be released some time today.

**Comment by mhamann** [comment]
Fixed via https://github.com/indexzero/nconf/releases/tag/v0.11.1

**Comment by sitvanit** [comment]
@mhamann Thank you for the fix.
I upgraded nconf to 0.11.1, but the ini version is still 1.3.5
Can you please check it?
Thanks again.

**Comment by guyguyon** [comment]
+1

**Comment by mhamann** [comment]
Sorry folks. Not sure what happened there. 0.11.2 is live now and should definitely pull in `ini@2.x`. Let me know if you run into any additional difficulties.
