### ISSUE TITLE
Inconsistency between npm artifact and source code in v0.x branch

### ISSUE THREAD

**Issue by anirudhb-sf** [indexzero/nconf#401]
The source code in branch `v0.x` brings in `async:^3.0.0` from [here](https://github.com/indexzero/nconf/blob/v0.x/package.json#L22), however the published [artifact](https://registry.npmjs.org/nconf/-/nconf-0.11.4.tgz) references `async:^1.4.0`. 
Request for a new version of `nconf` to be published so that it references `async:^3.0.0`

**Comment by mhamann** [comment]
The `v0.x` branch is slightly ahead of the released npm code. A new npm release will be published soon with the upgraded dependency.

**Comment by anirudhb-sf** [comment]
@mhamann any update on this? We depend on nconf 0.x version and the package is currently flagged due to its dependence on async:^1.4.0

**Comment by mhamann** [comment]
v0.12.0 has been released, which resolves this issue.
