### ISSUE TITLE
Is nconf abandoned?

### ISSUE THREAD

**Issue by carpii** [indexzero/nconf#415]
Last commit to master was Nov 2021, but theres a release from @mhamann  in Apr 2022.

Should I be using his fork, or maybe the v1.x.x branch for latest updates?

A bit confused on the state this project is in, thanks

**Comment by mhamann** [comment]
Still here and watching for bug reports and such. The project is stable and mostly in maintenance mode right now. It's being used all over the place in production.

If you find a security issue or bug, let us know and we'll look into it. Or better yet, open a PR. 🙂

**Comment by carpii** [comment]
thanks @mhamann

If I want to check out the code which relates to the 1.x npm release, is this just the 1.x.x branch on this repo?

**Comment by mhamann** [comment]
sure thing @carpii.

https://github.com/indexzero/nconf/tree/v0.x is stable (0.12.0 on npm)

https://github.com/indexzero/nconf/tree/master is v1.x beta.
