### ISSUE TITLE
Does nconf work with multiple files?

### ISSUE THREAD

**Issue by mstaicu** [indexzero/nconf#422]
I have the following example

```javascript
// server.js
import nconf from "nconf";

import { app } from "./app.js";

nconf.env({ lowerCase: true, parseValues: true, separator: "_" });
nconf.defaults({
  express: {
    port: 3000,
  },
});
```

This works, I get the correct value in `nconf.get("express:port")`, but if I do the same in `app.js` I get `undefined`. I tried this as well

```javascript
// index.js
import nconf from "nconf";

nconf.env({ lowerCase: true, parseValues: true, separator: "_" });
nconf.defaults({
  express: {
    port: 3000,
  },
});

import "./server.js";
```

And I get `undefined` in `server.js` when running `nconf.get("express:port")`

**Comment by mstaicu** [comment]
It seems that this is not working because of how ES Modules are resolved in node.js

**Comment by mstaicu** [comment]
Guess what I'm trying to find out is, can I initialize `nconf` once and then use it in all ESM files without redoing the `.env.argv.file`?

**Comment by mstaicu** [comment]
Figured it out, I used dynamic ESM imports, now this works

```javascript
import nconf from "nconf";

nconf.env({ lowerCase: true, parseValues: true, separator: "_" });

import('./server.js');
```

**Comment by mhamann** [comment]
Glad you figured it out! Thanks for posting your solution. I'm sure it'll be helpful to others as well.

**Comment by mstaicu** [comment]
Ended up with this file structure:

```bash
src
├── app.js
├── index.js
├── server.js
```

```javascript
// server.js

import nconf from "nconf";

import { app } from "./app.js";

var port = nconf.get("auth:express:port");

var close = graceful(
  app.listen(port, () => console.log(`Listening on port ${port}`))
);
```

```javascript
// index.js

import nconf from "nconf";

nconf.env({ lowerCase: true, parseValues: true, separator: "_" });

import("./server.js");
```

Running the web app server via `AUTH_EXPRESS_PORT=3000 node src/index.js`, using that variable only for the current shell, or you can set it for current shell and all processes started from current shell by first doing `export AUTH_EXPRESS_PORT=3000` and then running `node src/index.js`
