### ISSUE TITLE
nconf.overrides won't merge as expected

### ISSUE THREAD

**Issue by gusverdywid** [indexzero/nconf#71]
Calling nconf.overrides the second time will replace every options set the first time.

``` javascript
nconf.overrides({
  modules1: {prop1: 'abc', prop2: 'def'}
});

// The following will replace every object in nconf.overrides specified before
nconf.overrides({
  moduleA: {newProp: 'foo'}
});
```

Am I doing it right? Is it the intended behavior of `nconf.overrides`?

**Comment by adjohnson916** [comment]
@indexzero What if we want to provide overrides at the top-level of the object from multiple places? `set` seems to require a key.
