### ISSUE TITLE
custom key delimiter(e.g. change : with . or with _)

### ISSUE THREAD

**Issue by osher** [indexzero/nconf#95]
I saw nconf about a year ago, but I skipped it right away because of what I daresay the wierd choice for separator of keys sections, means:

```
nconf.get("foo:bar:thing") 
```

instead of the natural choice of: 

```
nconf.get("foo.bar.thing")  
```

like for example - optimist does.

At the time I had a configuration implementations so there was no real need (especially when it adhered to the natural choice, and no wierd stuff from other worlds like perl/ruby). 
But as life goes on and I move to new project that could not use the propriatry solutions I had in the old round - I land here again.

Small research shows that the `":"` seperator is basically hardcoded in two lines in `./lib/nconf/common`, and theoretically - can be easily featured as a custom option.

What I would like to know is:
- is there a valid reason to avoid using "." as seperator?
  
   and if not 
- will you be happy if I create a pull request to allow it?
  
   and if yes
- would the following be ok with  you?
  basically, what I think to do, is in .`./lib/nconf/common`:

```
//
// ### string delimiter 
//
comon.path.delimiter = ":"

//...
common.path = function (key) {
  return key == null ? [] : key.split(comon.path.delimiter);
};

//...
common.key = function () {
  return Array.prototype.slice.call(arguments).join(comon.path.delimiter);
};

```

And add the relevant vows sections for it in `./tests/nconf-test.js` I suppose...

```
).addBatch({
  "When using the nconf": {
    "and customizing key delimiter" : {
      "should use the provided delimiter" : function() {
          nconf.path.delimiter = ".";
          assert.equal(nconf.get('foo.bar.bazz'), 'buzz');
          assert.isTrue(nconf.set('foo.bar.thing', 'hurra'));
          assert.equal(nconf.get('foo.bar.thing'), 'hurra');
          nconf.path.delimiter = ":";  //put it back so other tests won't break
      }
    }
  }
})

```

)

what would result with the featured customization of

```
nconf = require('nconf')
nconf.path.delimiter = ".";

//.... load configs from all stores...

nconf.get("foo.bar.thing");

```

Thoughts?

**Comment by fyockm** [comment]
why isn't this in the fucking README?

**Comment by Oza94** [comment]
@fyockm please look at #160 and leave feedbacks. I would like to rewrite the docs for my team any suggestion or help will be appreciated.

**Comment by AmirSasson** [comment]
@jcrugzz how can i change this for all sources?
it is not reasonable to change just for one source. right?
my user code doesn't care what is the source of this config entry
